Sheaf of rings on Spec R
UniMath/UniMath pull request #1385
Opened 2021-09-04 19:04 UTC by timcherganov

#1316

2021-11-01 15:40 UTC, DanGrayson requested changes
Thank you for the contribution, it is appreciated.

In this review I make some minor comments.

2021-11-01 15:40 UTC, DanGrayson commented on UniMath/AlgebraicGeometry/Sheaf.v
> +          (F' : functor_data (open_category X)^op commring_precategory).
Why is F' just functor_data and not a functor?

2021-11-01 15:40 UTC, DanGrayson commented on UniMath/AlgebraicGeometry/Sheaf.v
> +  Definition restrict {A : hsubtype Open} (f : F (⋃ A)) (U : A) : F (pr1 U) :=
I think later code would be more readable if A were an explicit argument.

2021-11-01 15:40 UTC, DanGrayson commented on UniMath/AlgebraicGeometry/Sheaf.v
> +Section sheaf_commring_prop.
It would be desirable to handle sheaves of other types of things, too, not just rings.  Can you think of a way to do that?  If not, maybe the name of this file should be `SheavesOfRings.v` instead.

2021-11-01 15:40 UTC, DanGrayson commented on UniMath/AlgebraicGeometry/Spec.v
> +Arguments spec _ : clear implicits.
Maybe take advantage of the opportunity to capitalize `Spec` here.

2021-11-01 15:40 UTC, DanGrayson commented on UniMath/AlgebraicGeometry/Topology.v
> +  Definition TopologicalSpace : UU := ∑ X : hSet, isTopologicalSet X.
Good.  Later on we should phase out "TopologicalSet".

2021-11-03 08:24 UTC, timcherganov commented on UniMath/Algebra/RigsAndRings/Ideals.v
> +  Qed.
No particular reason. Do you think it's better to use `Defined` here?

2021-11-03 08:29 UTC, timcherganov commented on UniMath/AlgebraicGeometry/Sheaf.v
> +          (F' : functor_data (open_category X)^op commring_precategory).
There is no need in functoriality for the definition of locality and gluing.

2021-11-03 15:12 UTC, DanGrayson commented on UniMath/Algebra/RigsAndRings/Ideals.v
> +  Qed.
I always prefer "Defined" so things compute.  @benediktahrens may have a different opinion.

2021-11-03 16:40 UTC, benediktahrens commented on UniMath/Algebra/RigsAndRings/Ideals.v
> +  Qed.
1. Sometimes making things opaque is necessary for type-checking to terminate in a reasonable amount of time. 
2. I would be surprised if this particular proof would ever participate in a computation. Also, the particular shape of the proof does not make it seem particularly well-behaved in a computation.

Because of 2, I think it probably does not matter so much whether the proof is opaque or transparent. I would make it opaque myself, but I am fine with either choice.

2021-11-05 13:29 UTC, DanGrayson commented
@benediktahrens --

Look at the error: **The term "C" has type "precategory" while it is expected to have type "category".**

2021-11-05 19:11 UTC, benediktahrens commented
> @benediktahrens --
> 
> Look at the error: **The term "C" has type "precategory" while it is expected to have type "category".**

This is the error message from compiling the satellite repository https://github.com/UniMath/largecatmodules. I am in the process of fixing the satellites.

Compilation of UniMath/UniMath works fine with this PR.

2021-11-06 14:40 UTC, merged

2021-11-06 14:40 UTC, DanGrayson commented
Thank you for the contribution!