Created basic components of the definition of a curried monoidal cate…
UniMath/UniMath pull request #1465
Opened 2022-02-28 13:41 UTC by Kfwullaert

…gory. Maybe have to add coercions for the associator and unitors for readability? The CONTENTS.md file was not supposed to change, not sure how this happened.

2022-03-03 19:44 UTC, benediktahrens requested changes
Good stuff! Some small changes are necessary, see my comments.

2022-03-03 19:44 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +  Notation "f ⊗^{ T } g" := (tensoronmorphisms_from_tensor_cat T  _ _ _ _ f g) (at level 31).
@nmvdw : could you point us to best practices regarding notations? I believe that putting them into a submodule is a good idea, and importing the notations by opening the submodule. Can you point us to an example?

2022-03-03 19:44 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +    + exact (pr2 g).
This construction can probably be made quite a bit shorter, by removing `unfold...`, `simpl`.

2022-03-03 19:44 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +  Notation "ff ;; gg" := (comp_disp ff gg) (at level 50, left associativity, format "ff ;; gg").
This notation is already defined somewhere. See, e.g., `DisplayedCats/Equivalences.v` for how to bring it in, in particular, see `Local Open Scope mor_disp_scope.`

2022-03-03 19:44 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +        - exact ((pr2 dlu) x y a b f f').
Data and property should be constructed separately: we want the data to be transparent, the proof of the property to be opaque.
Here, one could put the proof of the property into an `abstract(...)` block.

The various `induction foo as [bar foobar]` tactics don't seem necessary.

2022-03-03 19:44 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +        - exact ((pr2 dru) x y a b f f').
As above.

2022-03-03 19:44 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +      - exact ((pr2 dα) x x' y y' z z' a a' b b' c c' f g h f' g' h').
As above.

2022-03-03 19:44 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +  Defined.
```suggestion
  Qed.
```

2022-03-03 19:44 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +  Defined.
```suggestion
  Qed.
```

2022-03-03 19:44 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +  Definition displayed_monoidal_category {M : monoidal_category} (D : disp_cat M) :=
Put type annotations everywhere.

```suggestion
  Definition displayed_monoidal_category {M : monoidal_category} (D : disp_cat M) : UU :=
```

2022-03-03 21:11 UTC, Kfwullaert commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +        - exact ((pr2 dlu) x y a b f f').
Concerning the seperation of the data and the property: If I understand it correctly, this abstract block makes the proof of the construction "invisible" in the same sense that "Defined" (resp. "Qed") makes the proof visible (resp. invisible). But don't we need this construction of the left unitor in order to proof the unitality of the forgetful functor (to show it is monoidal)?

2022-03-03 21:19 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +        - exact ((pr2 dlu) x y a b f f').
Yes, exactly. This is why the **proof part only** should be made opaque, that is, the part from line 106 to 114. The data part should remain transparent.

2022-03-04 15:20 UTC, rmatthes commented
I have an ideological remark: I find it unfortunate that the order of composition is turned around by using the notation `∘` instead of the usual `·` - usual for UniMath (not the applicative order of textbooks). This will ask for heavier efforts for a later migration to the new format of monoidal categories.

2022-03-04 16:06 UTC, DanGrayson commented
> ∘

Can't you just choose to use the operator appropriate for your context?

2022-03-04 16:31 UTC, benediktahrens commented
> I have an ideological remark: I find it unfortunate that the order of composition is turned around by using the notation `∘` instead of the usual `·` - usual for UniMath (not the applicative order of textbooks). This will ask for heavier efforts for a later migration to the new format of monoidal categories.

I don't anticipate any problems. This notation decodes to the normal composition. Furthermore, it is parse-only, so people not modifying the code here directly won't ever be bothered by it. But I might be missing something, of course.

2022-03-04 17:01 UTC, rmatthes commented
I agree that the user of the library will not be bothered with the opposite order. I still thought that such "parse-only" notation is meant to deal with legacy code.

2022-03-04 17:18 UTC, rmatthes commented
A non-ideological question: How does it come that the functor laws for the tensor are not part of the notion of a monoidal category in the curried style? I also do not see what `tensor_cat_struct` could be good for.

2022-03-04 17:26 UTC, benediktahrens commented
> I agree that the user of the library will not be bothered with the opposite order. I still thought that such "parse-only" notation is meant to deal with legacy code.

I agree that this code should eventually be written using `\cdot`, also to be in line with the corresponding code for displayed categories.

2022-03-04 17:39 UTC, benediktahrens commented
> The CONTENTS.md file was not supposed to change, not sure how this happened.

This file is built automatically using the information in the files `.package/files`.

2022-03-11 12:54 UTC, nmvdw commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +  Notation "f ⊗^{ T } g" := (tensoronmorphisms_from_tensor_cat T  _ _ _ _ f g) (at level 31).
Putting notations in a submodule can have advantages. The user of the code has then more control over what notations are in scope. We used it here:
- https://github.com/UniMath/UniMath/blob/master/UniMath/Bicategories/Limits/Products.v#L2070
- https://github.com/UniMath/UniMath/blob/master/UniMath/Bicategories/Core/Bicat.v#L1655

Note: if the notation is only for the specific section, then it should be declared `Local`: https://coq.github.io/doc/v8.10/refman/user-extensions/syntax-extensions.html#coq:cmd.local-notation. We used it here:
- https://github.com/UniMath/UniMath/blob/master/UniMath/Bicategories/Core/Bicat.v#L38
Local Notation only exists within the section in which it is declared, while without the `Local`-declaration, it persists even after the section.

I think all global notations should be put in a scope (which did not happen in these two lines of code). If they are not put in a scope, then the notations will always be present if the file is imported, and that can cause clashes.

2022-03-11 12:58 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +  Notation "f ⊗^{ T } g" := (tensoronmorphisms_from_tensor_cat T  _ _ _ _ f g) (at level 31).
A small addendum: I think that even non-local notations within sections are local. Try this code:
```
Section foo.
  Notation "'bar'" := nat.
  Check bar.
End foo.
Check bar.
```

2022-03-11 13:21 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalCurried.v
> +  Notation "f ⊗^{ T } g" := (tensoronmorphisms_from_tensor_cat T  _ _ _ _ f g) (at level 31).
Is it fair to say that a scope is like a namespace for notations?

2022-03-11 18:54 UTC, benediktahrens commented
@Kfwullaert : please address the requested changes, in particular those regarding notation, in a subsequent PR. I am merging this now.

2022-03-11 18:54 UTC, merged