Created curried bifunctors from a bicategorical point of view, adapte…
UniMath/UniMath pull request #1471
Opened 2022-03-14 21:25 UTC by Kfwullaert

…d the definition of monoidal categories and functors to work in this new "whiskered" setting. NOT READY TO BE MERGED since displayed monoidal categories, etc. still has to be adapted in this whiskered setting!

2022-03-15 12:04 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +Definition leftunitor_iso {C : category} {T : tensor C} {I : C} (lu : leftunitor T I) : UU := is_nat_z_iso (pr1 lu).
Why is the `pr1` necessary?

2022-03-15 12:07 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +    := ∏ (x y : C), (α x I y) · (x ⊗^{T}_{l} ((pr1 lu) y)) = ((pr1 ru) x) ⊗^{T}_{r} y.
Why is the `pr1` necessary?

2022-03-15 12:10 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalFunctorsWhiskered.v
> +  Lemma nattrans1'_nat (pt : preserves_tensor) : is_nat_trans functor1' functor2' (nattrans1'_data pt).
We need to improve this proof - if that is not possible, then there is something wrong with the definitions.

2022-03-15 12:15 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/WhiskeredBifunctors.v
> +  Lemma leftwhiskering_functor {A B C : category} (F : bifunctor_data A B C) (bli : bifunctor_leftidax F) (blc : bifunctor_leftcompax F) :
I would not be surprised if your problems in the proof mentioned elsewhere come from your transforming things into a functor to reuse the definition of `nat_trans`. This is probably a mistake, since Coq won't easily be able to infer what these functors are.

It is better not to use the notion `nat_trans`.

2022-03-15 12:23 UTC, Kfwullaert commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +Definition leftunitor_iso {C : category} {T : tensor C} {I : C} (lu : leftunitor T I) : UU := is_nat_z_iso (pr1 lu).
lu is a natural transformation, but it needs the data of the natural transformation, it doesn't work without the projection on the data, maybe there is no coercion from a natural transformation to its underlying data?

2022-03-15 12:33 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +Definition leftunitor_iso {C : category} {T : tensor C} {I : C} (lu : leftunitor T I) : UU := is_nat_z_iso (pr1 lu).
There is the following coercion
```
Coercion nat_trans_data_from_nat_trans_funclass : nat_trans >-> Funclass.
```
in `CategoryTheory.Core.NaturalTransformations`. Possibly it does not trigger because `leftunitor` is not unfolded to into `nat_trans`.

2022-03-15 16:27 UTC, rmatthes requested changes
the monoidal functors seem to need further discussion

2022-03-15 16:27 UTC, rmatthes commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +Definition leftunitor_iso {C : category} {T : tensor C} {I : C} (lu : leftunitor T I) : UU := is_nat_z_iso (pr1 lu).
Just add
`Identity Coercion leftunitorintonattrans: leftunitor >-> nat_trans.`
`Identity Coercion rightunitorintonattrans: rightunitor >-> nat_trans.`
to solve this problem.

2022-03-15 16:27 UTC, rmatthes commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +     (f ⊗^{T}_{1} (g ⊗^{T}_{1} h))∘(α x y z) = (α x' y' z')∘ ((f ⊗^{T}_{1} g) ⊗^{T}_{1} h).
For me, this could be just a derived equation (from three elementary ones with whiskering only - in the combinations ll, lr and rr).

2022-03-15 16:27 UTC, rmatthes commented on UniMath/CategoryTheory/Monoidal/MonoidalFunctorsWhiskered.v
> +  Lemma iso_stable_under_tranportation {C : category} {x y z : C} {f : C⟦x,y⟧} {pf : y=z} : (is_z_isomorphism f) → (is_z_isomorphism (transportf _ pf f)).
there should be an s in the last part of the identifier (this is just a typo)

2022-03-15 23:06 UTC, rmatthes reviewed
many good-looking changes

2022-03-15 23:06 UTC, rmatthes commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +    := ∏ (x y : C), (α x I y) · (x ⊗^{T}_{l} (pr1 lu y)) = ((pr1 ru) x) ⊗^{T}_{r} y.
cannot `pr1` now be left out here as well in both occurrences?

2022-03-16 16:18 UTC, rmatthes commented on UniMath/CategoryTheory/Monoidal/MonoidalFunctorsWhiskered.v
> +  Lemma isos_stable_under_tranportation {C : category} {x y z : C} {f : C⟦x,y⟧} {pf : y=z} : (is_z_isomorphism f) → (is_z_isomorphism (transportf _ pf f)).
I am sorry for having been imprecise before: the s is missing in tranportation.

2022-03-17 20:56 UTC, rmatthes commented on UniMath/CategoryTheory/Monoidal/MonoidalFunctorsWhiskered.v
> +  Lemma iso_stable_under_tranportf {C : category} {x y z : C} {f : C⟦x,y⟧} {pf : y=z} : (is_z_isomorphism f) → (is_z_isomorphism (transportf _ pf f)).
please an s after tran

2022-03-22 15:36 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalWhiskered.v
> +  Local Notation "α^{ M }_{ x , y , z }" := (associatordata_from_monoidalcatdata M x y z).
These notations should be obtained by opening a notation module?

2022-03-22 15:36 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalWhiskered.v
> +  Identity Coercion disptensor_into_dispbifunctor : disp_tensor >-> disp_bifunctor.
What is the purpose of this coercion?

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +Coercion leftunitor_from_monoidalcatdata : monoidalcategory_data >-> leftunitor.
I don't think having this coercion is a good idea.

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +    Check whiskerscommutes.
```suggestion
```

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalFunctorsWhiskered.v
> +Section local_helper_lemmas.
These lemmas should be moved into `CategoryTheory/Core/Isos`.

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +Coercion associatordata_from_monoidalcatdata : monoidalcategory_data >-> associator_data.
I don't think having this coercion is a good idea.

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +Coercion tensor_from_monoidalcatdata : monoidalcategory_data >-> tensor.
I don't think having this coercion is a good idea.

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalCategoriesWhiskered.v
> +  nat_trans (leftwhiskering_functor T (bifunctor_leftid T) (bifunctor_leftcomp T) I) (functor_identity C).
I suggest giving this definition directly, not in terms of `nat_trans` and `leftwhiskering_functor`.

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/TotalDisplayedMonoidalWhiskered.v
> +  Notation Tlu := totalcategory_leftunitor.
Where is this notation used?

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalFunctorsWhiskered.v
> +  Definition monoidalfunctor : UU :=
Change to `fmonoidal`?

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalFunctorsWhiskered.v
> +  Coercion strictlyunitpreserving_is_strong : preserves_unit_strictly >-> preserves_unit_strongly.
Useful?

2022-03-22 16:22 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/WhiskeredDisplayedBifunctors.v
> +  Import Notations.
Which Notations does this refer to? Maybe use a qualified name, such as `Import Foo.Notations.` to indicate the module of which `Notations` is a submodule?

2022-03-23 10:36 UTC, Kfwullaert commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalWhiskered.v
> +  Identity Coercion disptensor_into_dispbifunctor : disp_tensor >-> disp_bifunctor.
This coercion is for example already needed in the definition below of disp_associator_data. More precisely, In order to write "(xx \otimes\otimes_{DT} yy)", DT has to be of type "disp_bifunctor_data". If I would remove this coercion, then Coq doesn't know that DT is a disp_bifunctor (and by the coercion of disp_bifunctor >-> disp_bifunctor_data) in particular disp_bifunctor_data. So if I would remove this coercion, I would have to introduce the notation \otimes\otimes again for disp_tensor.

2022-03-23 10:49 UTC, Kfwullaert commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalWhiskered.v
> +  Coercion disp_tensor_from_dispmoncatdata : disp_monoidalcat_data >-> disp_tensor.
This is again helpful for using notation. If DMD would be the data of a displayed monoidal category, then, using this notation, we can write "xx \otimes\otimes_{DMD} yy", instead of having to write "xx \otimes\otimes_{disp_tensor_from_dispmoncatdata DMD} yy".

2022-03-23 11:05 UTC, Kfwullaert commented on UniMath/CategoryTheory/Monoidal/DisplayedMonoidalWhiskered.v
> +  Local Notation "α^{ M }_{ x , y , z }" := (associatordata_from_monoidalcatdata M x y z).
A related comment/question. These notations are used for when one wants to work with (non-displayed) monoidal categories. Should I also add analogous notations for displayed monoidal categories? For example, 
"dI_{DM}" := (dispunit_from_dispmoncatdata DM).
Then, when removing some of the coercions (mentioned in your comments below), I can just use these notations and it is more clear what data we need from the dispmoncatdata but we do not have to write for example dispunit_from_dispmoncatdata.

2022-03-23 20:42 UTC, Kfwullaert commented on UniMath/CategoryTheory/Monoidal/MonoidalFunctorsWhiskered.v
> +  Definition monoidalfunctor : UU :=
@benediktahrens Should only the definition of monoidalfunctor be changed to fmonoidal or also (for example) monoidalfunctor_laws to fmonoidal_laws?

2022-03-23 21:13 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/MonoidalFunctorsWhiskered.v
> +  Definition monoidalfunctor : UU :=
@Kfwullaert : Having consistent names is more important than having good names, hence yes, those should also be changed, I think.

2022-03-23 21:19 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/WhiskeredDisplayedBifunctors.v
> +  Lemma mor_disp_transportb_postwhisker
Is there not already such a lemma?

2022-03-23 21:19 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/WhiskeredDisplayedBifunctors.v
> +  Lemma mor_disp_transportb_prewhisker
Is there not already such a lemma?

2022-03-23 21:24 UTC, Kfwullaert commented on UniMath/CategoryTheory/Monoidal/WhiskeredDisplayedBifunctors.v
> +  Lemma mor_disp_transportb_postwhisker
There are mor_disp_transportf_prewhisker and mor_disp_transportf_postwhisker, but only those, not for backward transportation.

2022-03-23 21:30 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/WhiskeredDisplayedBifunctors.v
> +  Lemma mor_disp_transportb_postwhisker
Backward transport is a special case of forward transport, so the lemma about forward transport should apply here.

2022-03-25 08:20 UTC, benediktahrens commented
CI shows the following error:
```
--- checking every proof file is listed in one of the packages ---
error: *** file UniMath/CategoryTheory/Monoidal/MonoidalSectionsWhiskered.v not listed in appropriate file UniMath/*/.package/files
error: *** 1 unlisted proof files encountered
make: *** [Makefile:383: check-listing-of-proof-files] Error 1
```
Could you fix this?

2022-03-25 14:32 UTC, benediktahrens commented on UniMath/CategoryTheory/Monoidal/WhiskeredDisplayedBifunctors.v
> +  Lemma mor_disp_transportb_postwhisker
@Kfwullaert : please try to remove these lemmas.

2022-03-25 19:53 UTC, merged