Lemmas on (pre)fibrations
UniMath/UniMath pull request #1477
Opened 2022-03-25 10:13 UTC by Tobias-Schmude

The ultimate goal is to formalize [1, Theorem 4.1].
For now it contains the definition of prefibrations, some lemmas on (pre)cartesianness of compositions of morphisms, and the characterisation of fibrations as prefibrations where precartesian morphisms are stable under composition.

[1] Streicher, Thomas. "Fibered categories à la Jean Benabou." arXiv preprint arXiv:1801.02927 (2018).

2022-03-25 21:33 UTC, benediktahrens requested changes

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/CartesiannessOfComposites.v
> +Require Import UniMath.Foundations.All.
This import is duplicated from line 3.

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/Prefibrations.v
> +*)
Should this commented-out code be deleted?

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsPreliminaries.v
> +Qed.
These lemmas could go into the file `DisplayedCats.Fibrations`, avoiding fragmentation. This file should then be deleted.

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsCharacterisation.v
> +Qed.
Instead of using this lemma, one can just as well use `apply maponpaths.`. Let's remove it.

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsCharacterisation.v
> +Qed.
Instead of using this lemma, one can just as well use `apply maponpaths` or `maponpaths_2` or similar. Let's remove it.

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsCharacterisation.v
> +Search (transportf _ _ ?p = transportf _ _ ?p' -> ?p = ?p').
```suggestion
```

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsCharacterisation.v
> +Defined.
`transportb` is a special case of `transportf`, so you don't need this version and can use `transportf_cancel` instead.

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FiberDisplayedCategory.v
> +About pr1_transportf.
```suggestion
```

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FiberDisplayedCategory.v
> +About transport_compose'.
```suggestion
```

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/DisplayedDisplayedCategories.v
> +(** TODO: Defined displayed displayed categories as well as their total and fiber displayed displayed categories. *)
What is the purpose of this file?

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/CartesiannessWrtFibers.v
> +(** TODO: Lemmas L2&3 and Preliminaries *)
This file should be deleted.

2022-03-25 21:33 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/CartesiannessWrtComposites.v
> +(** TODO: Lemma L1 as well as preliminaries. *)
This file should be deleted?

2022-03-28 15:02 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/CartesiannessOfComposites.v
> +Require Import UniMath.Foundations.All.
Deleted

2022-03-28 15:03 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/Prefibrations.v
> +*)
I deleted it since you meant it has no advantage over the easier induction.

2022-03-28 15:03 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsPreliminaries.v
> +Qed.
I thought this was the point of the other pull request?

2022-03-28 15:03 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsCharacterisation.v
> +Qed.
done

2022-03-28 15:03 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsCharacterisation.v
> +Qed.
done

2022-03-28 15:03 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsCharacterisation.v
> +Search (transportf _ _ ?p = transportf _ _ ?p' -> ?p = ?p').
done

2022-03-28 15:14 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsCharacterisation.v
> +Defined.
Deleted `transportb_cancel` and replaced by transportf_cancel.

2022-03-28 15:14 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FiberDisplayedCategory.v
> +About pr1_transportf.
deleted

2022-03-28 15:24 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FiberDisplayedCategory.v
> +About transport_compose'.
done

2022-03-28 15:34 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/CartesiannessWrtComposites.v
> +(** TODO: Lemma L1 as well as preliminaries. *)
Why? Is it unusual to leave things to be filled in?

2022-03-28 15:35 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/DisplayedDisplayedCategories.v
> +(** TODO: Defined displayed displayed categories as well as their total and fiber displayed displayed categories. *)
The intent was to define what we discussed last time, but now it seems that I'm going in another direction (displayed Street fibrations), so I deleted this.

2022-03-28 19:00 UTC, benediktahrens commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/CartesiannessWrtComposites.v
> +(** TODO: Lemma L1 as well as preliminaries. *)
> Why? Is it unusual to leave things to be filled in?

No, but personal notes should be kept out of it.

2022-03-28 20:48 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsPreliminaries.v
> +Qed.
This file contains exactly those proofs: the factored-out lemma and the main one. The intention is to get rid of it of course.

2022-04-05 20:48 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/CartesiannessWrtFibers.v
> +(** TODO: Lemmas L2&3 and Preliminaries *)
done

2022-04-05 20:49 UTC, Tobias-Schmude commented on UniMath/CategoryTheory/DisplayedCats/MoreFibrations/CartesiannessWrtComposites.v
> +(** TODO: Lemma L1 as well as preliminaries. *)
done

2022-04-07 14:23 UTC, benediktahrens approved these changes

2022-04-07 14:23 UTC, merged