Added proof of univalence of the bicategory of univalent monoidal categories
UniMath/UniMath pull request #1527
Opened 2022-07-25 11:23 UTC by Kfwullaert

This pull request now makes use of the sigma construction of displayed bicategories.

2022-07-25 12:04 UTC, Kfwullaert commented
> Would there be a way to define a bicategory of monoidal categories on the basis of categories instead of univalent categories and only restrict to univalent categories for the purpose of getting the univalence result? But maybe this would be more of a hassle than to copy the code to a version without univalence in the ingredients and accordingly without univalence results.

@rmatthes
One needs to be able to restrict a displayed bicategory to a subbicategory (in our case a subtype of the type of objects in the sense of just adding a property to the objects) and in particular a result that the total category is a subcategory as well. 
@nmvdw What do you think?

2022-08-05 18:18 UTC, rmatthes reviewed
This is a preliminary review only on the two first important parts of the construction. Overall, it looks very good.

2022-08-05 18:18 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +  Lemma transport_of_bifunctor_map_is_pointwise {C : univalent_category}
I see that there is also a price to be paid for the currying approach.

2022-08-05 18:18 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +        use pathscomp0.
```suggestion
        etrans.
```

2022-08-05 18:18 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +        3: apply (pr2 te).
```suggestion
        2: apply (pr2 te).
```
`use pathscomp0` rarely serves a purpose

2022-08-06 18:05 UTC, rmatthes reviewed
Another intermediary feedback.

2022-08-06 22:13 UTC, rmatthes reviewed
all that is said about the left unitor also hold for the right unitor and the associator - they are developed in very close correspondence

2022-08-06 22:13 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/AssociatorLayer.v
> +  Defined.
This proof-checking takes excessively long time. Is it better when following my advice on the treatment of unitors?

2022-08-07 10:00 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +  Lemma swap_nat_along_zisos {C : category} {x1 x2 y1 y2 : C}
That is a good question, I have no idea why I called it like this.

2022-08-07 10:04 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +  Lemma transport_of_bifunctor_map_is_pointwise {C : univalent_category}
@rmatthes Yes indeed, we always need some transport lemma. For the whiskered approach, we would need another transportation lemma, something like transportation distributes over a pair. So in the end, it wouldn't have made such a big difference by using a whiskered approach.

2022-08-07 10:07 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/AssociatorLayer.v
> +In this file we construct one side of the second displayed layer above the bicategory of univalent categories, more precisely:
@rmatthes  With this I mean that the second layer consists of 2 sides, the associator and the unitors (although the left and right unitor are treated separately.

2022-08-07 10:26 UTC, rmatthes requested changes
comments on the final layer, including a question if the lax bicategory is desirable
the remaining `Admitted` must be addressed before a merge

2022-08-07 10:26 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +  Definition bicat_univlaxmon : bicat := total_bicat disp_univlaxmon.
This bicategory is a bit peculiar: the 1-cells are lax as expected, but also the objects are lax monoidal categories. Of course, that is sufficient to define lax monoidal functors, but it would even be so for the definition of (strong) monoidal functors. So, it this really a bicategory that should be put forward?

2022-08-07 10:42 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +  Admitted.
I guess I forgot about this. I'll check what happened here.

2022-08-07 10:44 UTC, rmatthes commented
The second layer for the unitors and the associator also redoes a generic construction several times. For example, one could just put
`Definition bidisp_lu_disp_prebicat : disp_prebicat tu_cat := disp_cell_unit_prebicat disp_lu_disp_cat_data.`
after having imported `UniMath.Bicategories.DisplayedBicats.Examples.DisplayedCatToBicat.`.
This can save three times 5 definitions and bring more clarity.

2022-08-07 10:49 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +  Definition bicat_univlaxmon : bicat := total_bicat disp_univlaxmon.
@rmatthes I understand your comment. I've been thinking about this as well. There is a "clean" solution for this, just add an extra displayed bicategory on top of this where you require that the unitors and associator become invertible and just using that you a full displayed bicategory of something univalent. However, then you don't have a nice separation between data and properties. If one wants to separate it, then one could do the following (which is less efficient):
Copy paste the files on the unitors/associator and where you add the inverse and on then add a displayed bicategory on the product displayed bicategory of e.g. the left unitor and the left unitor inverse where you then take a full subbicategory where you require them to really be inverses.

2022-08-07 11:01 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/AssociatorLayer.v
> +  Defined.
I've changed this as you proposed, which definitely looks a lot cleaner, but there is no difference in time.

2022-08-07 11:15 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +  Admitted.
It is finished now.

2022-08-07 11:16 UTC, Kfwullaert commented
> The second layer for the unitors and the associator also redoes a generic construction several times. For example, one could just put `Definition bidisp_lu_disp_prebicat : disp_prebicat tu_cat := disp_cell_unit_prebicat disp_lu_disp_cat_data.` after having imported `UniMath.Bicategories.DisplayedBicats.Examples.DisplayedCatToBicat.`. This can save three times 5 definitions and bring more clarity.

@rmatthes That is indeed an excellent point and worth changing. I'll try to do that.

2022-08-07 11:45 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +  Definition bicat_univlaxmon : bicat := total_bicat disp_univlaxmon.
For future uses, it seems that the ugly copying process should be preferred.

2022-08-07 11:45 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +    - repeat (use tpair).
```suggestion
    - repeat split.
```

2022-08-07 11:45 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/AssociatorLayer.v
> +In this file we construct one side of the second displayed layer above the bicategory of univalent categories, more precisely:
This is a useful view, but then the header of LeftUnitorLayer.v also claims to construct one side. Maybe better mention that three elements are treated in parallel and even rather similarly.

2022-08-07 11:45 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/AssociatorLayer.v
> +  Defined.
When playing your proofs, sometimes the huge goals took some time to show. Maybe you could save time by less unfolding. Of course, this would be pure experimentation.

2022-08-07 11:45 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +  Lemma transport_of_bifunctor_map_is_pointwise {C : univalent_category}
A somewhat sad conclusion.

2022-08-07 11:45 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +
What do you think about by proposal? It shows also fiddly type-checking problems.

2022-08-07 11:52 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +
I'm not able to go through it now in detail, so I'll come back to this.

2022-08-07 12:15 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +          ∏ {a1 a2 b1 b2 : C} (f : C⟦a1,a2⟧) (g : C⟦b1,b2⟧),
There are still 20 more warnings of this kind.

2022-08-07 12:16 UTC, rmatthes commented
I see that the blocking problem is solved, but I do not know how to mark this in the system.

2022-08-07 13:30 UTC, Kfwullaert commented
@rmatthes  Concerning disp_cell_unit_bicat, you are completely right, not only are the definitions more easy. Also the univalence proofs become even more easy. I didn't have to construct a factorization just a lemma. It is not even worth anymore to have 3 different files for the unitors and associators since it is now so short.

2022-08-07 14:02 UTC, Kfwullaert commented
@rmatthes I've changed the unitors and associator layers. Much shorter and easier now. I've changed the "message/overview of the file (i.e. the comment in the beginning of the file)" in the associator layer. Do you think that this is better? If so, I'll do the same change for the unitors. And if you agree I can also put the associators and unitors in the same file since they are so short now.

2022-08-07 14:06 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/AssociatorLayer.v
> +The second displayed layer we lay over the bicategory of univalent categories has the purppose of adding the unitors and the associator. In this file we construct the displayed bicategory which adds
```suggestion
The second displayed layer we lay over the bicategory of univalent categories has the purpose of adding the unitors and the associator. In this file we construct the displayed bicategory which adds all the data of the associator.
```

2022-08-07 14:07 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/AssociatorLayer.v
> +The total category corresponding to this displayed layer is the univalent bicategory defined as followed:
```suggestion
The total category corresponding to this displayed layer is the univalent bicategory defined as follows:
```
This is  a recurrent problem.

2022-08-07 14:09 UTC, rmatthes commented
@Kfwullaert I did not see those further simplifications coming. Very well observed. Yes, I think you should merge the three files of the second layer, even if they can be processed in parallel in their current form.

2022-08-07 14:27 UTC, Kfwullaert commented
> @Kfwullaert I did not see those further simplifications coming. Very well observed. Yes, I think you should merge the three files of the second layer, even if they can be processed in parallel in their current form.

It might be possible that other lemmas in that file, e.g. the locally groupoid and disp 2cells is a prop, also become a one liner and so that I don't need seperate lemmas for them.

2022-08-07 19:30 UTC, rmatthes commented
Still plenty of compilation warnings for a known cause.

2022-08-07 22:17 UTC, rmatthes reviewed
I should now have seen all the code.

2022-08-07 22:17 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +and that the result still holds when we replace lax by strong monoidal functors.
But I fear that the lax monoidal categories are not replaced by monoidal categories!

2022-08-08 12:57 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +        strong_lunitor (pr2 (assunitors_from_layer (pr1 C)  (pr12 C))).
@rmatthes They indeed give the same output, but I assume that this is because of the coercions you have from unitors_associator to the left unitor, right unitor and the associator. But I'll temporary remove the coercions as a test to be sure of this.

2022-08-08 13:03 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +        strong_lunitor (pr2 (assunitors_from_layer (pr1 C)  (pr12 C))).
@rmatthes It is indeed because of the coercions. If you want, I can remove the coercions, I only had to change something in the curriedmonoidalcategories file, in the other files nothing should have to be adapted.

2022-08-08 13:09 UTC, Kfwullaert commented
> Still plenty of compilation warnings for a known cause.

@rmatthes Should I remove the implicit binder declarations (all in the tensorlayer) in order to get rid of these warnings?

2022-08-08 21:35 UTC, rmatthes commented
@Kfwullaert Yes, please remove these curly variable binders.

2022-08-08 21:55 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +        strong_lunitor (pr2 (assunitors_from_layer (pr1 C)  (pr12 C))).
It is better to avoid this very unwanted effect - thank you.

2022-08-08 22:18 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/TensorLayer.v
> +
What is so difficult about this little piece of code?

2022-08-10 12:37 UTC, Kfwullaert commented
@rmatthes I think everything what should be in there is (if I did not forget anything). There is 1 lemma that I've admitted. The proof is commented out because, although the proof runs without a problem, the Qed is stuck in a loop. So could you have a look at that to see what is the issue?

2022-08-10 14:38 UTC, rmatthes commented
Where is file `UniMath/CategoryTheory/Monoidal/MonoidalCategoriesReordered.v`?

2022-08-10 17:58 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/CurriedMonoidalCategories.v
> +  Definition invertible_data {C : category}
The name suggests that all inside is data, but there are also all the proofs of `is_inverse_in_precat`.

2022-08-10 17:58 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +  Definition UMONCAT : bicat := total_bicat disp_univmon.
It would be good to indicate in a comment that this is the bicategory of monoidal categories (over univalent categories) and lax monoidal functors, both in a form that follows the constructions process that made it possible to carry out a modular proof of univalence.

2022-08-10 17:58 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +  Definition UMONCAT_strong : bicat := total_bicat disp_univstrongfunctor.
Similar to above, it would be good to indicate in a comment that this is the bicategory of monoidal categories (over univalent categories) and monoidal functors (non-lax, but not requiring functorial strength), both in a form that follows the constructions process that made it possible to carry out a modular proof of univalence.

2022-08-10 18:02 UTC, Kfwullaert commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/CurriedMonoidalCategories.v
> +  Definition invertible_data {C : category}
What do you think of "unitorsassociator_are_invertible"?

2022-08-10 18:08 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/CurriedMonoidalCategories.v
> +  Definition invertible_data {C : category}
Maybe `unitorsassociator_are_z_isos` - this would be more technical but lets the insiders know that there is data involved.

2022-08-11 18:04 UTC, rmatthes commented on UniMath/Bicategories/MonoidalCategories/UnivalenceMonCat/FinalLayer.v
> +  (* UMONCAT is the bicategory defined as follows:
```suggestion
  (* UMONCAT_strong is the bicategory defined as follows:
```

2022-08-12 10:35 UTC, rmatthes commented
@Kfwullaert 
> @rmatthes I think everything what should be in there is (if I did not forget anything). There is 1 lemma that I've admitted. The proof is commented out because, although the proof runs without a problem, the Qed is stuck in a loop. So could you have a look at that to see what is the issue?

I have solved this by playing a bit around with it - see PR no. 9 of your fork.

2022-08-12 10:59 UTC, rmatthes commented
I maybe have lost track of a previous statement on the following matter: the file CurriedMonoidalCategories.v is not dependent on the notion of bicategory and should be moved into UniMath/CategoryTheory/Monoidal in a subsequent PR that is confined to the renaming. But how is that positioned w.r.t. the already existing MonoidalCategoriesCurried.v in that directory?

2022-08-13 08:11 UTC, rmatthes requested changes
Monoidal/EquivalenceWhiskeredNonCurriedMonoidalCategories.v
in CategoryTheory/.package/files
needs to be moved downwards - for example right after 
Monoidal/MonoidalCategories.v

2022-08-13 11:22 UTC, rmatthes approved these changes

2022-08-13 11:23 UTC, merged