Rezk completion of a bicategory
UniMath/UniMath pull request #1612
Opened 2023-01-18 13:27 UTC by Kfwullaert

In this PR, a proof is constructed of how any bicategory is weakly bi-equivalent to a (locally) univalent bicategory, i.e. any bicategory admits a Rezk completion.

2023-01-26 09:55 UTC, nmvdw approved these changes

2023-01-26 09:55 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +            Functors.essentially_surjective H × fully_faithful H.
Why do you use `Functors.essentially_surjective` here instead of `essentially_surjective`? Also, perhaps this one can be moved to `CategoryTheory`.

2023-01-26 09:55 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +  Definition weak_local_equivalence
Both these definitions can be moved to `Pseudofunctor.v`. Also, the term `local weak equivalence` would make more sense.

2023-01-26 09:55 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +  Lemma functor_preserve_adj_equiv {C D : bicat}
Why do you use `Adjunctions.adjoint_equivalence` instead of `adjoint_equivalence`? Also, this statement can be moved to another file.

2023-01-26 09:55 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +  (* The naming here is 'inconsistent' because of the original naming convention used in
Sure. You can change the names in that file

2023-01-26 09:55 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +    use (nat_z_iso_comp (whiskering.pre_whisker_nat_z_iso _ _) _).
Why do you need `whiskering.pre_whisker_nat_z_iso` instead of `pre_whisker_nat_z_iso`?

2023-01-26 09:55 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +    : z_iso (C := R (hom x y))
Is the `(C := R (hom x y))` needed here?

2023-01-26 09:55 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +      use (nat_z_iso_comp (nat_z_iso_inv (PrecompEquivalence.nat_z_iso_pair _ _ _ _))).
`PrecompEquivalence` can be imported

2023-01-26 09:55 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +  Lemma LRB_lunitor_pre0 {x y : B} (f : B⟦x,y⟧)
What do you mean with this name?

2023-01-26 09:55 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +  Definition psfunctor_B_to_LRB_data
You should import the right file here

2023-01-27 08:54 UTC, Kfwullaert commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +            Functors.essentially_surjective H × fully_faithful H.
I use Functors.essentially_surjective because essentially_surjective automatically refers to essentially surjectiveness of pseudo-functors. If I move this in CategoryTheory, then this issue will not arise. But regarding the next comment, i.e. the definition of local_weak_equivalence, "Functors." still has to be added.

2023-01-27 09:25 UTC, Kfwullaert commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +      use (nat_z_iso_comp (nat_z_iso_inv (PrecompEquivalence.nat_z_iso_pair _ _ _ _))).
This is something that I don't understand. I have it actually imported, but nat_z_iso_pair is still not recognized without PrecompEquivalence.

2023-01-27 10:16 UTC, Kfwullaert commented
@nmvdw Currently there are two missing pieces (w.r.t. this review).
1: Regarding the composition of weak biequivalences, this is not something that I can put in Pseudofunctor.v (as it e.g. uses the composition of pseudofunctors).
2: Regarding the definition of Rezk completion of a category (as a weak equivalence into a univalent category), I've created a separate file for it (CategoryTheory/RezkCompletion.v), I find it strange to just have a file with one definition, so I could also instantiate it with e.g. the construction of the Rezk completion using the representable presheaves.

2023-01-27 19:13 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +            Functors.essentially_surjective H × fully_faithful H.
What do you think of renaming `essentially_surjective` for bicategories?

2023-01-27 19:15 UTC, nmvdw commented
> @nmvdw Currently there are two missing pieces (w.r.t. this review).
> 1: Regarding the composition of weak biequivalences, this is not something that I can put in Pseudofunctor.v (as it e.g. uses the composition of pseudofunctors).

The file `Pseudofunctor.v` currently contains several properties of pseudofunctors. Maybe we can give these their own file.

> 2: Regarding the definition of Rezk completion of a category (as a weak equivalence into a univalent category), I've created a separate file for it (CategoryTheory/RezkCompletion.v), I find it strange to just have a file with one definition, so I could also instantiate it with e.g. the construction of the Rezk completion using the representable presheaves.

This file might ultimately grow, because one could prove some properties about Rezk completions there.

2023-01-29 10:30 UTC, benediktahrens requested changes

2023-01-29 10:30 UTC, benediktahrens commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +In this file, it is proven how any bicategory is weakly biequivalent to a locally univalent bicategory.
```suggestion
In this file, it is shown how any bicategory is weakly biequivalent to a locally univalent bicategory.
```

2023-01-29 10:30 UTC, benediktahrens commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +As a consequence, we can conclude that any bicategory admit a Rezk completion (this is formulated in Bicategories/RezkCompletions/RezkCompletion.v
```suggestion
As a consequence, we can conclude that any bicategory admits a Rezk completion (this is formulated in Bicategories/RezkCompletions/RezkCompletion.v
```

2023-01-29 10:30 UTC, benediktahrens commented on UniMath/Bicategories/RezkCompletions/RezkCompletion.v
> +(* In this file, we combine the results that any bicategory is weak biequivalent to a locally univalent bicategory and
The name of this file is weird. If there are multiple completions (as indicated by the name of the directory), then the file name should be more descriptive, and indicate which one of the completions is contained in this file.

2023-01-29 10:30 UTC, benediktahrens commented on UniMath/CategoryTheory/RezkCompletion.v
> +End RezkCompletionUsingYoneda.
?
```suggestion
```

2023-01-30 10:24 UTC, Kfwullaert commented on UniMath/Bicategories/RezkCompletions/RezkCompletion.v
> +(* In this file, we combine the results that any bicategory is weak biequivalent to a locally univalent bicategory and
This is now solved

2023-01-30 10:25 UTC, Kfwullaert commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +  Definition psfunctor_B_to_LRB_data
This is solved, but because this comment was pointed differently, this is not considered to be solved by Git.

2023-01-30 10:47 UTC, benediktahrens commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +      use (nat_z_iso_comp (nat_z_iso_inv (PrecompEquivalence.nat_z_iso_pair _ _ _ _))).
@nmvdw : do you understand what is happening here?

2023-01-30 10:50 UTC, benediktahrens commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +  Lemma LRB_associator_pre_simpl_mor {x y z w : B} (f : B⟦x,y⟧) (g : B⟦y,z⟧) (h : B⟦z,w⟧)
Why is this called "Lemma"?

2023-01-30 10:52 UTC, nmvdw commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +      use (nat_z_iso_comp (nat_z_iso_inv (PrecompEquivalence.nat_z_iso_pair _ _ _ _))).
https://github.com/UniMath/UniMath/blob/5ed9fe58af25c218ac3d4a877b37785ac9089f5e/UniMath/CategoryTheory/PrecompEquivalence.v#L332

It seems to be a local lemma, so it is only meant to be used within that section.

2023-01-30 10:54 UTC, Kfwullaert commented on UniMath/Bicategories/RezkCompletions/BicatToLocalUnivalentBicat.v
> +      use (nat_z_iso_comp (nat_z_iso_inv (PrecompEquivalence.nat_z_iso_pair _ _ _ _))).
@nmvdw Thanks, I'll change this!

2023-02-01 15:48 UTC, benediktahrens commented on UniMath/Bicategories/PseudoFunctors/PseudoFunctor.v
> +  About FullyFaithful.
```suggestion
```

2023-02-01 16:17 UTC, benediktahrens approved these changes

2023-02-01 17:55 UTC, merged